Logging and argparse module added
CobbieCobbie/k-ary_tree_drawer pull request #3
Opened 2022-03-20 12:26 UTC by CobbieCobbie

Argparse:
Used to fetch $k$ and the height for the tree. Also, "--integer" or "-i" boolean sets whether its a grid or a plane

Logging:
Log dump into ${timestamp}_${k}-ary_tree_with_height_${h}.log

2022-03-21 13:38 UTC, locojoetive commented
Naise Sache!
Wie aktivie/deaktiviere ich die logs?

2022-03-21 13:47 UTC, CobbieCobbie commented
Ah, nice, hab ich bisher nicht bedacht. Füge ich auch als flag noch hinzu, thx

2022-03-30 21:33 UTC, CobbieCobbie commented
README adapted
Code PEPified, thanks @schlenger for fixing the logging issue :) works like a charm

2022-03-31 15:02 UTC, schlenger approved these changes

2022-03-31 15:23 UTC, locojoetive requested changes
Ich bekomme beim Ausführen diesen Error:
`AttributeError: module 'argparse' has no attribute 'BooleanOptionalAction'`
Mache ich was falsch?

EDIT:
_The argparse.BooleanOptionalAction feature is only available in Python 3.9 and above._
https://nono.ma/attributeerror-module-argparse-has-no-attribute-booleanoptionalaction

Wenn du das so wolltest solltest du das auch in die Readme adden

2022-03-31 15:23 UTC, locojoetive commented on k-ary_tree_drawer.py
> +    timestamp = time.gmtime()
Das sieht chic aus.
Vielleicht kann man Zeile 67 rausschmeissen und in Zeile 112 - 115 schreiben:
```
_time = time.gmtime() - timestamp 
print(f"The process took {_time.tm_min} minutes and {_time.tm_sec} seconds.")
```
Vorausgesetzt es gibt einen Subtraktions operator overload für `time`.

2022-03-31 15:27 UTC, locojoetive commented
Ich würde noch:
1. Die Logging Flag in die Readme aufnehmen
2. Alle expliziten string casts durch f-strings ersetzen, oder alle f-strings durch string casts - wegen Konsistenz

2022-03-31 16:12 UTC, merged